import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import type { CodebaseContext } from '../types/index.js';
import { logger } from '../utils/logger.js';

interface PackageJson {
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  name?: string;
  version?: string;
}

export class RepoAnalyzer {
  constructor(private readonly rootDir: string) {}

  analyze(): CodebaseContext {
    logger.info('RepoAnalyzer: starting analysis', { rootDir: this.rootDir });

    const stack = this.detectStack();
    const folderStructure = this.buildFolderTree(this.rootDir, 3);
    const patterns = this.detectPatterns();

    const context: CodebaseContext = {
      stack,
      rootDir: this.rootDir,
      folderStructure,
      patterns,
    };

    const claudeMd = this.generateClaudeMd(context);
    context.claudeMd = claudeMd;

    logger.info('RepoAnalyzer: analysis complete', { stack, patternsFound: Object.keys(patterns).length });

    return context;
  }

  writeClaudeMd(context: CodebaseContext): void {
    const claudeMdPath = join(this.rootDir, 'CLAUDE.md');
    const content = context.claudeMd ?? this.generateClaudeMd(context);
    writeFileSync(claudeMdPath, content, 'utf-8');
    logger.info('RepoAnalyzer: wrote CLAUDE.md', { path: claudeMdPath });
  }

  private detectStack(): string[] {
    const pkgPath = join(this.rootDir, 'package.json');
    if (!existsSync(pkgPath)) return ['unknown'];

    const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8')) as PackageJson;
    const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
    const stack: string[] = [];

    const detectors: Array<[string, string]> = [
      ['next', 'Next.js'],
      ['react', 'React'],
      ['vue', 'Vue'],
      ['svelte', 'Svelte'],
      ['express', 'Express'],
      ['fastify', 'Fastify'],
      ['hono', 'Hono'],
      ['@supabase/supabase-js', 'Supabase'],
      ['prisma', 'Prisma'],
      ['drizzle-orm', 'Drizzle ORM'],
      ['tailwindcss', 'Tailwind CSS'],
      ['vitest', 'Vitest'],
      ['jest', 'Jest'],
      ['typescript', 'TypeScript'],
    ];

    for (const [pkg, label] of detectors) {
      if (pkg in allDeps) stack.push(label);
    }

    return stack.length > 0 ? stack : ['Node.js'];
  }

  private detectPatterns(): Record<string, string> {
    const patterns: Record<string, string> = {};

    const checks: Array<[string, string, string]> = [
      ['src/app', 'routing', 'Next.js App Router'],
      ['src/pages', 'routing', 'Next.js Pages Router'],
      ['src/routes', 'routing', 'file-based routing'],
      ['src/lib', 'lib', 'shared utilities in src/lib/'],
      ['src/components', 'components', 'React components in src/components/'],
      ['src/__tests__', 'testing', 'co-located tests in __tests__/'],
    ];

    for (const [dir, key, value] of checks) {
      if (existsSync(join(this.rootDir, dir))) {
        patterns[key] = value;
      }
    }

    return patterns;
  }

  private buildFolderTree(dir: string, maxDepth: number, depth = 0): string {
    if (depth > maxDepth) return '';

    const IGNORE = new Set([
      'node_modules', '.git', 'dist', '.next', 'out', '.turbo',
      'coverage', '.agentOS/state', '__pycache__',
    ]);

    const lines: string[] = [];
    let entries: string[];

    try {
      entries = readdirSync(dir).sort();
    } catch {
      return '';
    }

    for (const entry of entries) {
      if (IGNORE.has(entry) || entry.startsWith('.')) continue;

      const fullPath = join(dir, entry);
      const relPath = relative(this.rootDir, fullPath);
      const indent = '  '.repeat(depth);

      try {
        const stat = statSync(fullPath);
        if (stat.isDirectory()) {
          lines.push(`${indent}${entry}/`);
          const sub = this.buildFolderTree(fullPath, maxDepth, depth + 1);
          if (sub.length > 0) lines.push(sub);
        } else {
          lines.push(`${indent}${entry}`);
        }
      } catch {
        // skip unreadable entries
      }

      void relPath; // suppress unused var warning
    }

    return lines.join('\n');
  }

  private generateClaudeMd(context: CodebaseContext): string {
    return [
      '# CLAUDE.md — Codebase Context',
      '',
      '> Auto-generated by AgentOS RepoAnalyzer. Do not edit manually.',
      '',
      '## Project Stack',
      context.stack.map((s) => `- ${s}`).join('\n'),
      '',
      '## Root Directory',
      context.rootDir,
      '',
      '## Folder Structure',
      '```text',
      context.folderStructure,
      '```',
      '',
      '## Detected Patterns',
      Object.entries(context.patterns).length > 0
        ? Object.entries(context.patterns).map(([k, v]) => `- **${k}**: ${v}`).join('\n')
        : '- No specific patterns detected',
      '',
      '## Agent Instructions',
      '- Follow existing naming conventions found in the codebase',
      '- Use TypeScript strict mode — no `any`, no non-null assertions without comment',
      '- Place tests in `__tests__/` directories co-located with source',
      '- Emit file artifacts using ```file:path fences',
    ].join('\n');
  }
}
